### ISSUE TITLE
Minor fixes in `Building TensorFlow-0.9.0 on Piz Daint`

### ISSUE THREAD

**Issue by Robin-des-Bois** [eth-cscs/TensorFlow#1]
I just followed the instructions in [Building TensorFlow-0.9.0 on Piz Daint](https://github.com/eth-cscs/TensorFlow/wiki/TensorFlow-0.9.0-Daint-GPU-build) to compile tensorflow. 

They work. One probelm was that installing wheel (using the pip from the custom module) caused an error: 
```
$ pip install wheel
Collecting wheel
 Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: wheel
Exception:
Traceback (most recent call last):
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(pa

th)
  File "/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/apps/daint/UES/5.2.UP04/sandbox-ds/easybuild/software/Python/3.5.1-CrayGNU-2016.03-rpath/lib/python3.5/site-packages/wheel-0.29.0.dist-info'
```

Without `wheel` its not possible to run `bazel-bin/tensorflow/tools/pip_package/build_pip_package` successfully. 

Using a virtualenv wheel gets installed automatically and everything works! 

I attached the updated markdown file (see [TensorFlow.wiki.zip](https://github.com/eth-cscs/TensorFlow/files/353223/TensorFlow.wiki.zip)) including some other small path fixes.

Thank you very much for this great support! I am deeply impressed!

**Comment by mschoengens** [comment]
Hi Robin,

Have you tried to load the pre-build python module with TensorFlow support as described here:

https://github.com/eth-cscs/TensorFlow/wiki/tensorflow-0.9.0-daint

Best,
Marcel

**Comment by gppezzi** [comment]
@Robin-des-Bois 

The building instructions were mostly to keep track of what we did and we didn't expect that you would rebuild since if the available module is supposed to be working (please let us know if that is not the case).

We actually did use virtualenv for creating the module TensorFlow/0.9.0-Python3-gpu, but thanks for the feedback and for pointing that out. 

If you really need to build TF from sources, one suggestion for the next time is to use /dev/shm for speeding up the build process (scratch can be very slow for such builds).
```
export TEST_TMPDIR=/dev/shm/$USER/
```

**Comment by Robin-des-Bois** [comment]
@gppezzi 

The available module works fine.

But somehow the module wasn't loaded after executing `salloc -N1`. After reloading the module on the new node, `srun python /apps/daint/UES/5.2.UP04/sandbox-ds/tensorflow/TensorFlow/build-0.9.0/basic-tf-gpu-test.py` produced the expected output. 

But since I (and probably others as well) need some [custom operations] (https://www.tensorflow.org/versions/r0.9/how_tos/adding_an_op/index.html) I need to compile tensorflow myself. Therefore it would be nice if you could update wiki. 

Unfortunately, there is no directory `/dev/shm/$USER/` for my account (and other normal user accounts). But you are right. Building took quite some time.

**Comment by gppezzi** [comment]
The proper way of running TF is through a batch job, we will provide a slurm example to avoid this issue with `salloc`.

If building TF from source is a commom use case, then it makes sense for us to provide instructions, thanks for the heads up.

Finally, /dev/shm should be writable, you just need to create a directory there. I've updated the wiki build instructions,  please keep us posted if that works for you.
